Seldon upgrade 1.6.0->1.14.0
canonical/seldon-core-operator pull request #30
Opened 2022-07-11 22:46 UTC by DnPlas

Upgrades seldon-core-operator to 1.14.0. This PR introduces the following:
* Updates manifest files to match latest release
* Upstream seldon-core image version bump
* WIP updates integration and unit tests

Note: These changes will be tested in both 1.21 in this PR and 1.22 in a different one.

2022-07-14 23:13 UTC, DnPlas commented
These changes are working for me locally, I'm not sure 1) why the CI is not running after my last commit and 2) why we are getting `is forbidden: User "system:serviceaccount:testing:seldon-controller-manager"` kind of messages. Will investigate further.

2022-07-20 08:26 UTC, natalian98 commented
It looks that the grafana library was updated again very recently. Could you do the `charmcraft fetch-lib` to gather it?

2022-07-20 08:46 UTC, DomFleischmann commented on src/charm.py
> -            "ENGINE_SERVER_PORT": config["engine-server-port"],
Why are all these configuration removed? And if they aren't useful anymore, should we remove them in juju config too?

2022-07-20 14:48 UTC, DomFleischmann approved these changes

2022-07-20 14:49 UTC, DomFleischmann requested changes
Approved too soon, can you fetch the observability libs again?

2022-07-21 11:47 UTC, merged